version: '3.9'

services:
  web:
    image: gsor-frontend:latest
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://gitapi.loica.top:5453}
    ports:
      - "33334:80"
    restart: unless-stopped
    networks:
      - core-net

networks:
  core-net:
    external: true
